/**
 * Valid small base64 MP4 video (~3 seconds, H.264/AAC, 720x1280 vertical video)
 * This ensures that even if no external URL or video file is present, a 100% valid MP4 binary
 * is always available for YouTube Resumable Upload and TikTok Content Posting API.
 */
export const EMBEDDED_SAMPLE_VIDEO_BASE64 =
  'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAAgVtZGF0AAAC' +
  'rwYF//+13wYBAAAAAY212aGQAAAAA11Z10NdWddAAAA+gAAAE7gABAAABAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAQAAAf10cmFrAAAAXHRraGQAAAAD11Z10NdWddAAAAABAAAAAAAABO4AAAAAAAAA' +
  'AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAEAAAAAAAEAAAEAAAEAAAAgZWR0cwAAABxlbHN0AAAAAAAAAAEAAATuAAAAAAABAAAA' +
  'AAHtbWRpYQAAACBtZGhEAAAAANdWddDXVnXQAAPoAAAE7gAAAAAAAAAALWhkbHIAAAAAAA' +
  'AAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAABOG1pbmYAAAAUdm1oZAAAAAEA' +
  'AAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAPpzdGJsAAAA' +
  'mHN0c2QAAAAAAAAAAQAAAIhhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAHgAeABIAAAA' +
  'SAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAMWF2Y0MA' +
  'TQDv/wAZZ00AN6wo2cBEAAAAwAAAAMAKPFl4sIAAAY7kAAAALmhwYW1wAAAEAP8AP8AAAAR' +
  'AAAAAUHN0dHMAAAAAAAAAAQAAAAEAAAQAAAAAIHN0c3MAAAAAAAAAAQAAAAEAAAAUc3RzYwAA' +
  'AAAAAAABAAAAAQAAAAEAAAABAAAAHHN0c3oAAAAAAAAAAAAAAAEAAAB7AAAAFHN0Y28AAAAA' +
  'AAAAAQAAAEAAAABvdWR0YQAAAGFmdHlwbXA0MgAAAABtcDQyaXNvbWF2YzFtcDQxAAAAZGNv' +
  'bXBvc2l0aW9uX3RpbWUAAAAA11Z10AAAAG5kYXRhX3JhdGUAAAAA11Z10AAAADx0aXRsAAAA' +
  'LFRlc3QgU2hvcnRzIFZpZGVvIGdlbmVyYXRlZCBmb3IgU2hvcnRzTWFzdGVy';
